name: future_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  alt_sms_autofill: ^1.0.0
  animate_do: ^2.1.0
  bot_toast: ^4.0.3
  cloud_firestore: ^4.0.4
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  firebase_storage: ^11.0.4
  flashy_tab_bar2: ^0.0.4
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.5+1
  flutter_feed_reaction: ^0.0.5
  flutter_localizations:
    sdk: flutter
  flutter_social_textfield: ^0.1.2
  flutter_story_list: ^1.0.4+2
  flutter_svg: ^1.1.6
  font_awesome: ^5.10.1
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^5.1.1
  iconsax: ^0.0.8
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  lottie: ^2.0.0
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  pretty_dio_logger: ^1.1.1
  responsive_framework: ^0.2.0
  sentry: ^6.14.0
  sentry_flutter: ^6.14.0
  shared_preferences: ^2.0.15
  story_view: ^0.14.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/locales/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal_Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal_Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal_Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal_Bold.ttf
          weight: 700
