name: future_chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  advstory: ^0.2.1
  agora_rtc_engine: any
  alt_sms_autofill: ^1.0.0
  animate_do: ^2.1.0
  appinio_social_share: ^0.2.0
  bot_toast: ^4.0.3
  bubble: ^1.2.1
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.0.4
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  diamond_dial_fab: ^0.0.3
  dio: ^4.0.0
  file_picker: ^5.2.2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  firebase_dynamic_links: ^5.0.6
  firebase_messaging: ^14.0.4
  firebase_storage: ^11.0.4
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.0
  flutter_contacts: ^1.1.5+1
  flutter_link_previewer: ^3.2.0
  flutter_localizations:
    sdk: flutter
  flutter_social_textfield: ^0.1.2
  flutter_svg: ^1.1.6
  font_awesome: ^5.10.1
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^5.1.1
  iconsax: ^0.0.8
  image_picker_plus: ^0.5.5+2
  insta_image_viewer: ^1.0.2
  insta_like_button: ^0.1.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  like_button: ^2.0.5
  lottie: ^2.0.0
  pandabar: any
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.4
  responsive_framework: ^0.2.0
  rich_text_view: ^1.1.0
  sentry: ^6.14.0
  sentry_flutter: ^6.14.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  story_view: ^0.14.0
  timeago: ^3.3.0
  uni_links: ^0.5.1
  url_launcher: ^6.1.6
  video_thumbnail: ^0.5.3
  video_viewer: ^1.2.7
  animations: ^2.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: 2.0.1
  flutter_native_splash: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  null: "#ffffff"
  image: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/locales/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal_Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal_Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal_Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal_Bold.ttf
          weight: 700
